server:
  port: 8082
  servlet:
    context-path: /notification
app:
  dbName: notification-service

spring:
  application:
    name: ${app.dbName}
  data:
    mongodb:
      uri:  ${MONGODB_URL_CONNECTION}/${app.dbName}?authSource=admin
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.famtwen.notification.event.NotificationEvent
        spring.json.use.type.headers: false

notification:
  brevo-url: ${BREVO_URL:https://api.brevo.com}
  name: ${BREVO_NAME}
  email: ${BREVO_EMAIL}
  brevo-apikey: ${BREVO_APIKEY:Key}


